sequences:
  - elephant
  - bear
  - bmx-bumps
  - boat
  - boxing-fisheye
  - breakdance-flare
  - bus
  - car-turn
#  - cat-girl
  - classic-car
  - color-run
  - crossing
  - dance-jump
  - dancing
#  - disc-jockey
  - dog-agility
  - dog-gooses
  - dogs-scale
  - drift-turn
  - drone
  - flamingo
  - hike
  - hockey
  - horsejump-low
  - kid-football
  - kite-walk
  - lady-running
  - lindy-hop
  - longboard
  - lucia
  - mallard-fly
  - mallard-water
  - miami-surf
  - motocross-bumps
  - motorbike
  - night-race
  - paragliding
  - planes-water
  - rallye
  - rhino
  - rollerblade
  - schoolgirls
  - scooter-board
  - scooter-gray
  - sheep
  - skate-park
  - snowboard
  - soccerball
  - stroller
  - stunt
  - surf
  - swing
  - tennis
  - tractor-sand
  - train
  - tuk-tuk
  - upside-down
  - varanus-cage
  - walking
